---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data-dir
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: "longhorn"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-dir
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: "longhorn"

