apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      version: 25.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik
  interval: 5m
  values:
# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
    image:
      tag: v3.0.0-beta4
    service:
      type: LoadBalancer
      annotations:
        kube-vip.io/loadbalancerIPs: 10.1.1.1
        external-dns.alpha.kubernetes.io/hostname: traefik.k8s.thaibert.com
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true  # Allow external-dns to pick up annotations from IngressRoute objects
    logs:
      general:
        level: DEBUG
      access:
        enabled: true
    ports:
      # Traefik `entrypoints` are defined here
      # NB: Entrypoint names can be at most 15 characters
      web: null
      websecure: null

      intweb:
        port: 8000
        expose: true
        exposedPort: 80
        protocol: TCP

      intwebsecure:
        port: 8443
        expose: true
        exposedPort: 443
        protocol: TCP

      extwebsecure:
        port: 7443
        expose: false # TODO
        exposedPort: 7443
        protocol: TCP

    ingressRoute:
      dashboard:
        enabled: false
      
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  url: https://traefik.github.io/charts


