- name: "add containerd apt repo"
  become: true
  block:
    - name: "download armored gpg key"
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
    - name: "add repository"
      # TODO: replace "noble" with actual, current codename
      # (see https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository)
      ansible.builtin.apt_repository: 
        repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu noble stable'
        state: present
  
- name: "sudo apt update"
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: "sudo apt install containerd"
  become: true
  ansible.builtin.apt:
    pkg:
      - containerd.io

- name: "set systemd cgroup driver"
  become: true
  ansible.builtin.shell: |
    sudo mkdir -p /etc/containerd
    sudo containerd config default | sudo tee /etc/containerd/config.toml
    sudo sed --in-place 's|SystemdCgroup\s*\=\s*false|SystemdCgroup \= true|g' /etc/containerd/config.toml

- name: "restart and enable systemd service"
  become: true
  ansible.builtin.systemd_service:
    service: containerd
    state: restarted
    enabled: true
    daemon_reload: true
