apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: 1.5.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
  interval: 5m
  values:
    # https://github.com/longhorn/charts/blob/v1.5.x/charts/longhorn/values.yaml
    persistence:
      defaultClassReplicaCount: 2
      defaultDataLocality: strict-local
    defaultSettings:
      # Settings in longhorn-ui. (Only applies to fresh install; to change, edit directly in longhorn-ui).
      createDefaultDiskLabeledNodes: true
      defaultReplicaCount: 2
      defaultDataLocality: strict-local

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-dashboard
  namespace: longhorn-system
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik.k8s.thaibert.com
spec:
  entryPoints:
  - intweb
  - intwebsecure
  routes:
  - match: "Host(`longhorn.k8s.thaibert.com`)"
    kind: Rule
    services:
      - name: longhorn-frontend
        port: 80
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 30m
  url: https://charts.longhorn.io


