apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- patch: |
    # Enable DriftDetection
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --feature-gates=DetectDrift=true,CorrectDrift=true
  target:
    kind: Deployment
    name: helm-controller
