- name: "install spiderpool"
  run_once: true
  delegate_to: "{{ groups.controlplane_nodes[0] }}" # the first controlplane node will have had "helm" installed
  become: true
  block:
    - ansible.builtin.set_fact:
        spiderpool_valuesfile: /tmp/spiderpool.values.yaml
    - name: "place spiderpool valuesfile on target node"
      ansible.builtin.copy:
        src: "{{ inventory_dir }}/resources/spiderpool.values.yaml"
        dest: "{{ spiderpool_valuesfile }}"
    - name: "helm install"
      ansible.builtin.shell:
        cmd: >
          helm upgrade --install
          spiderpool
          spiderpool
          --repo https://spidernet-io.github.io/spiderpool
          --version 1.0.1
          --values "{{ spiderpool_valuesfile }}"
          --namespace kube-system
          --kubeconfig /etc/kubernetes/admin.conf
