- name: "install spiderpool"
  run_once: true
  delegate_to: "{{ groups.controlplane_nodes[0] }}" # the first controlplane node will have had "helm" installed
  become: true
  block:
    - ansible.builtin.set_fact:
        spiderpool_valuesfile: /tmp/spiderpool.values.yaml
    - name: "place spiderpool valuesfile on target node"
      ansible.builtin.copy:
        src: "{{ inventory_dir }}/resources/spiderpool.values.yaml"
        dest: "{{ spiderpool_valuesfile }}"
    - name: "helm install"
      kubernetes.core.helm:
        release_name: spiderpool
        chart_version: 1.0.1
        release_namespace: kube-system
        values_files:
          - "{{ spiderpool_valuesfile }}"
        chart_repo_url: https://spidernet-io.github.io/spiderpool
        chart_ref: spiderpool
        atomic: true
        kubeconfig: /etc/kubernetes/admin.conf

