apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flannel
  namespace: networking
spec:
  releaseName: flannel
  chart:
    spec:
      chart: flannel
      version: v0.24.0
      sourceRef:
        kind: HelmRepository
        name: flannel
  interval: 1m
  values:
    #podCidr: "10.244.0.0/16"

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: flannel
  namespace: networking
spec:
  interval: 30m
  url: https://flannel-io.github.io/flannel/

